services:
  - type: web
    name: stress-detection-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn stress_detection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stress_detection.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DB_PATH
        value: /opt/render/project/data/db.sqlite3
      # 🔒 Add these manually in Render dashboard under Environment:
      # - key: SECRET_KEY
      #   value: your-secret-key
      # - key: DEBUG
      #   value: False
      # - key: ALLOWED_HOSTS
      #   value: stress-detection-for-it-professionals.onrender.com