services:
  - type: web
    name: stress-detection-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn strees_dection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: strees_dection.settings
      - key: PYTHON_VERSION
        value: 3.10
      # Add any other secret keys here
