services:
  - type: web
    name: stress-detection-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn strees_dection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: strees_dection.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true  # Render generates a secure key, or set manually
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: stress-detection-for-it-professionals.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: EMAIL_HOST_USER
        value: suragms2000@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: jwsv cemy mkkt mwcd
        sync: false