services:
  - type: web
    name: stress-detection-django
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn stress_detection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stress_detection.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DB_PATH
        value: /opt/render/project/data/db.sqlite3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: stress-detection-for-it-professionals.onrender.com
      - key: EMAIL_HOST_USER
        value: suragms2000@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: jwsv cemy mkkt mwcd

  - type: web
    name: rasa-server
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install rasa
    startCommand: rasa run --cors "*" --enable-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: worker
    name: rasa-actions
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install rasa-sdk
    startCommand: rasa run actions
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
