services:
  - type: web
    name: stress-detection-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip                     # ✅ Upgrade pip (optional but good)
      pip install -r requirements.txt               # ✅ Install dependencies
      python manage.py makemigrations
      python manage.py migrate                     # ✅ Apply migrations
      python manage.py collectstatic --noinput      # ✅ Collect static files
    startCommand: startCommand: gunicorn stress_detection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: strees_dection.settings
      - key: PYTHON_VERSION
        value: 3.10
      # 🔒 Add secret keys like DEBUG=False, SECRET_KEY, ALLOWED_HOSTS, etc.
