# Generated by Django 4.2.20 on 2025-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usersregister_confirm_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentime',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time of the screen activity', null=True),
        ),
        migrations.AddField(
            model_name='screentime',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if the timer is currently active'),
        ),
        migrations.AddField(
            model_name='screentime',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Start time of the screen activity', null=True),
        ),
        migrations.AlterField(
            model_name='screentime',
            name='duration',
            field=models.DurationField(blank=True, help_text='Total screen time duration', null=True),
        ),
    ]
