# Generated by Django 4.2.20 on 2025-04-21 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_screentime_end_time_screentime_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentime',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('SOCIAL', 'Social Media'), ('ENTERTAINMENT', 'Entertainment'), ('PRODUCTIVITY', 'Productivity'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Other')], default='OTHER', help_text='Category of the screen activity', max_length=20),
        ),
        migrations.AddField(
            model_name='usersregister',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
