# Generated by Django 4.2.20 on 2025-04-22 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_screentime_category_usersregister_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(help_text='Type of feature (e.g., keystroke_speed, heart_rate_variability)', max_length=100)),
                ('feature_value', models.FloatField(help_text='Extracted feature value')),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.TextField(default='{}', help_text='Additional context for the feature (JSON string)')),
            ],
        ),
        migrations.CreateModel(
            name='StressPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(help_text='Type of pattern (e.g., high_stress, low_stress)', max_length=100)),
                ('confidence_score', models.FloatField(help_text='Confidence in pattern recognition (0-1)')),
                ('recognized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Description of the recognized pattern')),
                ('features', models.ManyToManyField(help_text='Features contributing to this pattern', to='app.extractedfeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('KEYBOARD', 'Keyboard Activity'), ('SCREEN_TIME', 'Screen Time'), ('APP_USAGE', 'Application Usage'), ('VOICE', 'Voice Pattern'), ('WEARABLE', 'Wearable Data')], max_length=20)),
                ('raw_data', models.TextField(default='{}', help_text='Raw data before processing (JSON string)')),
                ('cleaned_data', models.TextField(default='{}', help_text='Cleaned and normalized data (JSON string)')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True, help_text='Indicates if data passed cleaning checks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(help_text='Type of prediction (e.g., stress_level, burnout_risk)', max_length=100)),
                ('prediction_value', models.FloatField(help_text='Predicted value (e.g., stress score)')),
                ('confidence_score', models.FloatField(help_text='Confidence in prediction (0-1)')),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_version', models.CharField(help_text='Version of the ML model used', max_length=50)),
                ('stress_pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stresspattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.AddField(
            model_name='extractedfeature',
            name='processed_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processeddata'),
        ),
        migrations.AddField(
            model_name='extractedfeature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister'),
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(help_text='Type of anomaly (e.g., outlier_heart_rate, unusual_typing)', max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Description of the anomaly')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Indicates if anomaly has been reviewed')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.extractedfeature')),
                ('processed_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.processeddata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
    ]
