# Generated by Django 4.2.20 on 2025-05-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_extractedfeature_stresspattern_processeddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assessment',
        ),
    ]
