# Generated by Django 4.2.20 on 2025-05-11 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_feedback_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user'], name='app_feedbac_user_id_4776c9_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['date'], name='app_feedbac_date_a9de79_idx'),
        ),
    ]
