# Generated by Django 4.2.20 on 2025-05-11 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='app_feedbac_user_id_4776c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='app_feedbac_date_a9de79_idx',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when feedback was submitted'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(help_text="User's feedback text"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.usersregister'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', 'date'], name='app_feedbac_user_id_378749_idx'),
        ),
    ]
